### ISSUE TITLE
How to make pull on raspberry pi. 

### ISSUE THREAD

**Issue by kanokkk** [iloveicedgreentea/plex-webhook-automation#1]
Hi, i am trying to set it up on a raspberry pi and I am having some problems at step 1 where i should make the pull - what is the command in ssh to do this? I did try to search google for an answer with no luck...

**Comment by iloveicedgreentea** [comment]
I assume you mean docker pull, in that case you would want to try 

`docker run -p 9999:9999 -v (path to your config):/config.json -it ghcr.io/iloveicedgreentea/plex-webhook-automation:master`

Then point your webhook to the ip and port 9999 running that thing and you should see stuff happen in the logs

**Comment by kanokkk** [comment]
Is it possible to install this on the pi? 
I get this error:
pi@raspberrypi:~ $ pi@raspberrypi:~ $ docker run -p 9999:9999 -v autoez:/config.json -it ghcr.io/il                                            oveicedgreentea/plex-webhook-automation:master
Unable to find image 'ghcr.io/iloveicedgreentea/plex-webhook-automation:master'                                             locally
master: Pulling from iloveicedgreentea/plex-webhook-automation
fc251a6e7981: Pull complete
ce9f6ccd450e: Pull complete
Digest: sha256:f3c1b05f119ea79585cabb6ac0ab1559167df31b023f2b8963fe2d8222b999f0
Status: Downloaded newer image for ghcr.io/iloveicedgreentea/plex-webhook-automation:master
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v6) and no specific platform was requested
exec /app: exec format error

**Comment by iloveicedgreentea** [comment]
I’m only building for x64 right now. I can add a multi target later. In the meantime you can clone the repo and build the container locally or you can compile the binary instead
