### ISSUE TITLE
Error when playing movie

### ISSUE THREAD

**Issue by kanokkk** [iloveicedgreentea/plex-webhook-automation#14]
Hi, 

What is causing this error and how do I correct it? 
It worked before, but after I got a new internet provider and router, my IP has changed, I have corrected all IP in the config file and in webhooks in Plex.

ime="06-23-2023 10:36:30" level=debug msg="decodeWebhook: Received event: media.play"
time="06-23-2023 10:36:30" level=debug msg="!!! Your Player UUID is c39f564b427565dc-com-plexapp-android !!!!!"
time="06-23-2023 10:36:30" level=debug msg="ProcessWebhook:  Media type is: movie"
time="06-23-2023 10:36:30" level=debug msg="ProcessWebhook:  Media title is: DELETED"
time="06-23-2023 10:36:30" level=info msg="Processing media type: movie"
time="06-23-2023 10:36:30" level=error msg="expected element type MediaContainer> but have HTML>" 
There is a < before mediacontainer and HTML, but the full line would not show so I deleted the <

**Comment by kanokkk** [comment]
time="06-23-2023 10:36:30" level=error msg="expected element type <MediaContainer> but have <html>"

**Comment by iloveicedgreentea** [comment]
Did you whitelist the new IP in Plex? Usually that error means an auth issue. I’m going to improve it so it’s more clear in the logs
