### ISSUE TITLE
Wont Load BEQ Filter - no ezbeq devices provided. Can't load

### ISSUE THREAD

**Issue by kchaing** [iloveicedgreentea/plex-webhook-automation#17]
This is the first time I am setting up plexwebautomation so not sure if this is a new issue or not but I am running latest 2.0.7 pre-release. When I run your app, I see that it says it successfully unloads the BEQ filter via api call to ezbeq. However, when I play a movie, it throws an error saying "no ezbeq devices provided. Can't load". BEQ filters dont seem to unload either. I am not using HA or MQTT either as I just want to use this for the plex/EZBEQ automation.

**To Reproduce**
1. Run automation app
2. Play movie
3. No BEQ filter is loaded, BEQ filters also dont seem to be unloaded (tried manually loading filter in EZBEQ and filter still seems to be applied after automation says "unloading BEQ filters". I am using slot 3 for EzBEQ so I tested slot 1 and slot 3 just to see if there is a bug with the new slot config option.

**Expected behavior**
BEQ filter should load and unload when media is played/unplayed

**Debug logs**
pi@htpcpi:~/plex-webhook-automation $ go run .
DEBU[07-05-2023 10:42:18] Started in debug mode...
INFO[07-05-2023 10:42:18] Starting server
INFO[07-05-2023 10:42:18] PlexWorker started
INFO[07-05-2023 10:42:18] Started with ezbeq enabled
DEBU[07-05-2023 10:42:18] Using method GET
DEBU[07-05-2023 10:42:18] Header is set to false
DEBU[07-05-2023 10:42:18] Using url http://192.168.50.170:8080/api/2/devices
DEBU[07-05-2023 10:42:18] Headers from req map[]
INFO[07-05-2023 10:42:18] Minidsp worker started
DEBU[07-05-2023 10:42:18] Started minidsp worker with ezbeq
DEBU[07-05-2023 10:42:18] Using method GET
DEBU[07-05-2023 10:42:18] Header is set to false
DEBU[07-05-2023 10:42:18] Using url http://192.168.50.170:8080/api/2/devices
DEBU[07-05-2023 10:42:18] Headers from req map[]
DEBU[07-05-2023 10:42:18] BEQ payload: map[string]models.BeqDevices{"master":models.BeqDevices{Name:"master", MasterVolume:-0, Mute:false, Slots:[]models.BeqSlots{models.BeqSlots{ID:"1", Last:"Empty", Active:false, Gain1:0, Gain2:0, Mute1:false, Mute2:false}, models.BeqSlots{ID:"2", Last:"Empty", Active:false, Gain1:0, Gain2:0, Mute1:false, Mute2:false}, models.BeqSlots{ID:"3", Last:"Empty", Active:true, Gain1:0, Gain2:0, Mute1:false, Mute2:false}, models.BeqSlots{ID:"4", Last:"Ready Player One", Active:false, Gain1:0, Gain2:0, Mute1:false, Mute2:false}}}}
DEBU[07-05-2023 10:42:18] BEQ payload: map[string]models.BeqDevices{"master":models.BeqDevices{Name:"master", MasterVolume:-0, Mute:false, Slots:[]models.BeqSlots{models.BeqSlots{ID:"1", Last:"Empty", Active:false, Gain1:0, Gain2:0, Mute1:false, Mute2:false}, models.BeqSlots{ID:"2", Last:"Empty", Active:false, Gain1:0, Gain2:0, Mute1:false, Mute2:false}, models.BeqSlots{ID:"3", Last:"Empty", Active:true, Gain1:0, Gain2:0, Mute1:false, Mute2:false}, models.BeqSlots{ID:"4", Last:"Ready Player One", Active:false, Gain1:0, Gain2:0, Mute1:false, Mute2:false}}}}
DEBU[07-05-2023 10:42:18] Unloading ezBEQ profiles
DEBU[07-05-2023 10:42:18] using endpoint /api/1/devices/master/filter/3
DEBU[07-05-2023 10:42:18] Using method DELETE
DEBU[07-05-2023 10:42:18] Header is set to false
DEBU[07-05-2023 10:42:18] Using url http://192.168.50.170:8080/api/1/devices/master/filter/3
DEBU[07-05-2023 10:42:18] Headers from req map[]
DEBU[07-05-2023 10:42:22] decodeWebhook: Received event: media.resume
DEBU[07-05-2023 10:42:22] !!! Your Player UUID is jz85n1sp8tuwzffn8e6nergr !!!!!
DEBU[07-05-2023 10:42:22] ProcessWebhook:  Media type is: movie
DEBU[07-05-2023 10:42:22] ProcessWebhook:  Media title is: Moana
INFO[07-05-2023 10:42:22] Processing media type: movie
DEBU[07-05-2023 10:42:22] Event Router: Found edition:
DEBU[07-05-2023 10:42:22] Codecs from plex received: English (DTS 5.1), English (DTS 5.1)
DEBU[07-05-2023 10:42:22] Atmos: false - DD+: false
DEBU[07-05-2023 10:42:22] Event Router: Found codec: DTS 5.1
DEBU[07-05-2023 10:42:22] Event Router: Received codec: DTS 5.1
DEBU[07-05-2023 10:42:22] Event Router: Got media type of: movie
DEBU[07-05-2023 10:42:22] Event Router: Using search model: { 2016 DTS 5.1   false  0 false  [] []}
DEBU[07-05-2023 10:42:22] Event Router: media.resume received
DEBU[07-05-2023 10:42:22] Unloading ezBEQ profiles
DEBU[07-05-2023 10:42:22] getPlexMovieDb: Got tmdb ID from plex - tmdb://277834
ERRO[07-05-2023 10:42:22] no ezbeq devices provided. Can't load
DEBU[07-05-2023 10:42:31] decodeWebhook: Received event: media.pause
DEBU[07-05-2023 10:42:31] !!! Your Player UUID is jz85n1sp8tuwzffn8e6nergr !!!!!
DEBU[07-05-2023 10:42:31] ProcessWebhook:  Media type is: movie
DEBU[07-05-2023 10:42:31] ProcessWebhook:  Media title is: Moana
INFO[07-05-2023 10:42:31] Processing media type: movie
DEBU[07-05-2023 10:42:31] Event Router: Found edition:
DEBU[07-05-2023 10:42:31] Codecs from plex received: English (DTS 5.1), English (DTS 5.1)
DEBU[07-05-2023 10:42:31] Atmos: false - DD+: false
DEBU[07-05-2023 10:42:31] Event Router: Found codec: DTS 5.1
DEBU[07-05-2023 10:42:31] Event Router: Received codec: DTS 5.1
DEBU[07-05-2023 10:42:31] Event Router: Got media type of: movie
DEBU[07-05-2023 10:42:31] Event Router: Using search model: { 2016 DTS 5.1   false  0 false  [] []}
DEBU[07-05-2023 10:42:31] Event Router: media.pause received
DEBU[07-05-2023 10:42:31] Unloading ezBEQ profiles
no ezbeq devices provided. Can't loadDEBU[07-05-2023 10:44:20] decodeWebhook: Received event: media.stop
DEBU[07-05-2023 10:44:20] !!! Your Player UUID is jz85n1sp8tuwzffn8e6nergr !!!!!
DEBU[07-05-2023 10:44:20] ProcessWebhook:  Media type is: movie
DEBU[07-05-2023 10:44:20] ProcessWebhook:  Media title is: Moana
INFO[07-05-2023 10:44:20] Processing media type: movie
DEBU[07-05-2023 10:44:20] Event Router: Found edition:
DEBU[07-05-2023 10:44:40] decodeWebhook: Received event: media.play
DEBU[07-05-2023 10:44:40] !!! Your Player UUID is jz85n1sp8tuwzffn8e6nergr !!!!!
DEBU[07-05-2023 10:44:40] ProcessWebhook:  Media type is: episode
DEBU[07-05-2023 10:44:40] ProcessWebhook:  Media title is: Canvassing
ERRO[07-05-2023 10:44:50] Event Router: error getting codec from plex, can't continue: error getting codec. no session found with uuid jz85n1sp8tuwzffn8e6nergr
INFO[07-05-2023 10:44:50] Processing media type: episode
DEBU[07-05-2023 10:44:50] Event Router: Found edition:
DEBU[07-05-2023 10:44:50] Codecs from plex received: English (DTS-HD MA 5.1), DTS-HD MA 5.1 (English)
DEBU[07-05-2023 10:44:50] Atmos: false - DD+: false
DEBU[07-05-2023 10:44:50] Event Router: Found codec: DTS-HD MA 5.1
DEBU[07-05-2023 10:44:50] Event Router: Received codec: DTS-HD MA 5.1
DEBU[07-05-2023 10:44:50] Event Router: Got media type of: episode
DEBU[07-05-2023 10:44:50] Event Router: Using search model: { 2009 DTS-HD MA 5.1   false  0 false  [] []}
DEBU[07-05-2023 10:44:50] Event Router: media.play received
DEBU[07-05-2023 10:44:50] Unloading ezBEQ profiles
DEBU[07-05-2023 10:44:50] getPlexMovieDb: Got tmdb ID from plex - tmdb://397622
ERRO[07-05-2023 10:44:50] no ezbeq devices provided. Can't load
DEBU[07-05-2023 10:45:02] decodeWebhook: Received event: media.stop
DEBU[07-05-2023 10:45:02] !!! Your Player UUID is jz85n1sp8tuwzffn8e6nergr !!!!!
DEBU[07-05-2023 10:45:02] ProcessWebhook:  Media type is: episode
DEBU[07-05-2023 10:45:02] ProcessWebhook:  Media title is: Canvassing
INFO[07-05-2023 10:45:02] Processing media type: episode
DEBU[07-05-2023 10:45:02] Event Router: Found edition:

**Desktop (please complete the following information):**
 - OS: Raspbian GNU/Linux 11 (bullseye)
 - Version [e.g. 22]: Linux 5.15.73-v7l+
 - Deployment method: binary
 - EZBEQ version: v1.0.4

**Additional context**

**Comment by iloveicedgreentea** [comment]
Can you post your config also

**Comment by iloveicedgreentea** [comment]
Are you running the latest ezbeq and minidsp firmware?

Go to http://ezbeq.local:8080/api/doc/

Open  2/devices, execute the get request, and send me the output there

**Comment by kchaing** [comment]
ezbeq.local doesnt resolve for me but if I replace with IP address it works:
http://192.168.50.170:8080/api/doc/
Request URL: http://192.168.50.170:8080/api/2/devices

{
  "master": {
    "type": "minidsp",
    "name": "master",
    "masterVolume": 0,
    "mute": false,
    "slots": [
      {
        "id": "1",
        "last": "10 Minutes Gone",
        "active": true,
        "gains": [
          {
            "id": "1",
            "value": 5
          },
          {
            "id": "2",
            "value": 5
          }
        ],
        "mutes": [
          {
            "id": "1",
            "value": false
          },
          {
            "id": "2",
            "value": false
          }
        ],
        "canActivate": true,
        "inputs": 2,
        "outputs": 4
      },
      {
        "id": "2",
        "last": "Empty",
        "active": false,
        "gains": [
          {
            "id": "1",
            "value": 1.5
          },
          {
            "id": "2",
            "value": 1.5
          }
        ],
        "mutes": [
          {
            "id": "1",
            "value": false
          },
          {
            "id": "2",
            "value": false
          }
        ],
        "canActivate": true,
        "inputs": 2,
        "outputs": 4
      },
      {
        "id": "3",
        "last": "10 Minutes Gone",
        "active": false,
        "gains": [
          {
            "id": "1",
            "value": 0
          },
          {
            "id": "2",
            "value": 0
          }
        ],
        "mutes": [
          {
            "id": "1",
            "value": false
          },
          {
            "id": "2",
            "value": false
          }
        ],
        "canActivate": true,
        "inputs": 2,
        "outputs": 4
      },
      {
        "id": "4",
        "last": "Ready Player One",
        "active": false,
        "gains": [
          {
            "id": "1",
            "value": 2
          },
          {
            "id": "2",
            "value": 2
          }
        ],
        "mutes": [
          {
            "id": "1",
            "value": false
          },
          {
            "id": "2",
            "value": false
          }
        ],
        "canActivate": true,
        "inputs": 2,
        "outputs": 4
      }
    ]
  }
}

**Comment by iloveicedgreentea** [comment]
are you sure you are running 2.0.7?

**Comment by kchaing** [comment]
I think you are right, I am on master (commit [5de4ba5]) and looks like the version is not the latest. I assumed it was v2.0.7 because the latest commit was from two weeks ago. Should I be switching to develop branch or try a different release? Its not clear to me what release I am actually running.

**Comment by iloveicedgreentea** [comment]
if you are using docker its tag 2.0.7 otherwise use the develop branch

**Comment by kchaing** [comment]
switched to develop branch, reran and am now getting different errors:

````
pi@htpcpi:~/plex-webhook-automation $ go run .
DEBU[07-05-2023 18:41:02] Started in debug mode...
INFO[07-05-2023 18:41:02] Starting server
INFO[07-05-2023 18:41:02] Minidsp worker started
INFO[07-05-2023 18:41:02] PlexWorker started
INFO[07-05-2023 18:41:02] Started with ezbeq enabled
DEBU[07-05-2023 18:41:02] Using method GET
DEBU[07-05-2023 18:41:02] Header is set to false
DEBU[07-05-2023 18:41:02] Using url http://192.168.50.170:8080/api/2/devices
DEBU[07-05-2023 18:41:02] Headers from req map[]
DEBU[07-05-2023 18:41:02] Started minidsp worker with ezbeq
DEBU[07-05-2023 18:41:02] Using method GET
DEBU[07-05-2023 18:41:02] Header is set to false
DEBU[07-05-2023 18:41:02] Using url http://192.168.50.170:8080/api/2/devices
DEBU[07-05-2023 18:41:02] Headers from req map[]
DEBU[07-05-2023 18:41:03] BEQ payload: map[string]models.BeqDevices{"master":models.BeqDevices{Name:"master", MasterVolume:-0, Mute:false, Slots:[]models.BeqSlots{models.BeqSlots{ID:"1", Last:"10 Minutes Gone", Active:false, Gain1:0, Gain2:0, Mute1:false, Mute2:false}, models.BeqSlots{ID:"2", Last:"Empty", Active:false, Gain1:0, Gain2:0, Mute1:false, Mute2:false}, models.BeqSlots{ID:"3", Last:"Empty", Active:true, Gain1:0, Gain2:0, Mute1:false, Mute2:false}, models.BeqSlots{ID:"4", Last:"Ready Player One", Active:false, Gain1:0, Gain2:0, Mute1:false, Mute2:false}}}}
DEBU[07-05-2023 18:41:03] BEQ device: "master"
DEBU[07-05-2023 18:41:03] BEQ payload: map[string]models.BeqDevices{"master":models.BeqDevices{Name:"master", MasterVolume:-0, Mute:false, Slots:[]models.BeqSlots{models.BeqSlots{ID:"1", Last:"10 Minutes Gone", Active:false, Gain1:0, Gain2:0, Mute1:false, Mute2:false}, models.BeqSlots{ID:"2", Last:"Empty", Active:false, Gain1:0, Gain2:0, Mute1:false, Mute2:false}, models.BeqSlots{ID:"3", Last:"Empty", Active:true, Gain1:0, Gain2:0, Mute1:false, Mute2:false}, models.BeqSlots{ID:"4", Last:"Ready Player One", Active:false, Gain1:0, Gain2:0, Mute1:false, Mute2:false}}}}
DEBU[07-05-2023 18:41:03] BEQ device: "master"
DEBU[07-05-2023 18:41:03] Discovered devices: [{master -0 false [{1 10 Minutes Gone false 0 0 false false} {2 Empty false 0 0 false false} {3 Empty true 0 0 false false} {4 Ready Player One false 0 0 false false}]}]
DEBU[07-05-2023 18:41:03] adding device master
DEBU[07-05-2023 18:41:03] Device names: [master]
DEBU[07-05-2023 18:41:03] Unloading ezBEQ profiles
DEBU[07-05-2023 18:41:03] using endpoint /api/1/devices/master/filter/3
DEBU[07-05-2023 18:41:03] Using method DELETE
DEBU[07-05-2023 18:41:03] Header is set to false
DEBU[07-05-2023 18:41:03] Using url http://192.168.50.170:8080/api/1/devices/master/filter/3
DEBU[07-05-2023 18:41:03] Headers from req map[]
DEBU[07-05-2023 18:41:13] ProcessWebhook: Received valid multipart form
DEBU[07-05-2023 18:41:13] decoding payload
DEBU[07-05-2023 18:41:13] decodeWebhook: Received event: media.play
DEBU[07-05-2023 18:41:13] !!! Your Player UUID is jz85n1sp8tuwzffn8e6nergr !!!!!
DEBU[07-05-2023 18:41:13] ProcessWebhook:  Media type is: movie
DEBU[07-05-2023 18:41:13] ProcessWebhook:  Media title is: Moana
INFO[07-05-2023 18:41:13] Processing media type: movie
DEBU[07-05-2023 18:41:13] Event Router: Found edition:
DEBU[07-05-2023 18:41:13] Event Router: Got media type of: movie
DEBU[07-05-2023 18:41:13] Event Router: Using search model: &models.SearchRequest{TMDB:"", Year:2016, Codec:"", PreferredAuthor:"aron7awol", Edition:"", SkipSearch:true, EntryID:"", MVAdjust:0, DryrunMode:false, MediaType:"", Devices:[]string{"master"}, Slots:[]int{3}}
DEBU[07-05-2023 18:41:13] Event Router: media.play received
DEBU[07-05-2023 18:41:13] Unloading ezBEQ profiles
DEBU[07-05-2023 18:41:13] using endpoint /api/1/devices/master/filter/3
DEBU[07-05-2023 18:41:13] Using method DELETE
DEBU[07-05-2023 18:41:13] Header is set to false
DEBU[07-05-2023 18:41:13] Using url http://192.168.50.170:8080/api/1/devices/master/filter/3
DEBU[07-05-2023 18:41:13] Headers from req map[]
DEBU[07-05-2023 18:41:13] pausing plex
DEBU[07-05-2023 18:41:13] using params: commandID=0&machineIdentifier=jz85n1sp8tuwzffn8e6nergr&type=movie
DEBU[07-05-2023 18:41:13] Plex response: <html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html>
DEBU[07-05-2023 18:41:13] using params: commandID=0&machineIdentifier=jz85n1sp8tuwzffn8e6nergr&type=movie
DEBU[07-05-2023 18:41:13] Plex response: <html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x34 pc=0x397fac]

goroutine 12 [running]:
github.com/iloveicedgreentea/go-plex/homeassistant.(*HomeAssistantClient).ReadEnvyAttributes(0x0)
        /home/pi/plex-webhook-automation/homeassistant/ha.go:130 +0x24
github.com/iloveicedgreentea/go-plex/handlers.waitForHDMISync(0x2111dd0, 0x1ebe0a0, 0x0, 0x1e2a080)
        /home/pi/plex-webhook-automation/handlers/plex_handler.go:167 +0x1a0
created by github.com/iloveicedgreentea/go-plex/handlers.mediaPlay
        /home/pi/plex-webhook-automation/handlers/plex_handler.go:197 +0x2b4
exit status 2
```

**Comment by chippoman** [comment]
I'm in the same boat. I had this working in the past until I started getting "no ezbeq devices provided. Can't load" error. Found this issue, pulled the v2.0.7 docker image and am running into the same error:

time="07-19-2023 19:19:15" level=debug msg="ProcessWebhook:  Media title is: The Flash"
time="07-19-2023 19:19:15" level=info msg="Processing media type: movie"
time="07-19-2023 19:19:15" level=debug msg="Event Router: Found edition: "
time="07-19-2023 19:19:15" level=debug msg="Event Router: Got media type of: movie "
time="07-19-2023 19:19:15" level=debug msg="Event Router: Using search model: &models.SearchRequest{TMDB:\"\", Year:2023, Codec:\"\", PreferredAuthor:\"\", Edition:\"\", SkipSearch:true, EntryID:\"\", MVAdjust:0, DryrunMode:false, MediaType:\"\", Devices:[]string{\"master\"}, Slots:[]int{1}}"
time="07-19-2023 19:19:15" level=debug msg="Event Router: media.play received"
time="07-19-2023 19:19:15" level=debug msg="Unloading ezBEQ profiles"
time="07-19-2023 19:19:15" level=debug msg="using endpoint /api/1/devices/master/filter/1"
time="07-19-2023 19:19:15" level=debug msg="Using method DELETE"
time="07-19-2023 19:19:15" level=debug msg="Header is set to false"
time="07-19-2023 19:19:15" level=debug msg="Using url http://192.168.0.210:8080/api/1/devices/master/filter/1"
time="07-19-2023 19:19:15" level=debug msg="Headers from req map[]"
time="07-19-2023 19:19:15" level=debug msg="pausing plex"
time="07-19-2023 19:19:15" level=debug msg="using params: commandID=0&machineIdentifier=2879a23a97e0bcbe-com-plexapp-android&type=movie"
time="07-19-2023 19:19:15" level=debug msg="Plex response: <html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html>"
time="07-19-2023 19:19:15" level=debug msg="using params: commandID=0&machineIdentifier=2879a23a97e0bcbe-com-plexapp-android&type=movie"
time="07-19-2023 19:19:15" level=debug msg="Plex response: <html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html>"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x768c86]

goroutine 56 [running]:
github.com/iloveicedgreentea/go-plex/homeassistant.(*HomeAssistantClient).ReadEnvyAttributes(0x0)
        /go/src/app/homeassistant/ha.go:130 +0x26
github.com/iloveicedgreentea/go-plex/handlers.waitForHDMISync(0xc000260f58?, 0xc000260fd0?, 0x663ac6?, 0xc000248000)
        /go/src/app/handlers/plex_handler.go:167 +0x177
created by github.com/iloveicedgreentea/go-plex/handlers.mediaPlay
        /go/src/app/handlers/plex_handler.go:197 +0x35f

**Comment by iloveicedgreentea** [comment]
anything other than 0.0.6 is still experimental. I havent had much time to work on this but I plan on making the 2.x features stable probably by this weekend.

**Comment by iloveicedgreentea** [comment]
Please try v2.1

I tested multiple functions and it works for me. Make sure to update the config file
