### ISSUE TITLE
match profile close to source

### ISSUE THREAD

**Issue by kanokkk** [iloveicedgreentea/plex-webhook-automation#5]
Would it be possible to add a feature to allow for near match profiles to sync - I have had a couple of no match with for example DD+ atmos in the profile and my source having DDP 5.1 Atmos (Engelsk EAC3). 
I assume that this is not the same codec?

**Comment by iloveicedgreentea** [comment]
DDP, DD+, E-AC-3 EC-3

these are all the same thing. I can update the matching logic to be a little looser

**Comment by iloveicedgreentea** [comment]
Can you post debug logs which will show the exact name of the codecs (title and extended title) so I can confirm it via a test?

**Comment by iloveicedgreentea** [comment]
Please try using a tag of 0.0.7 to test this out. It should match your DD+ atmos titles now. Please test regular DD+ and typical Atmos as well to make sure. I don't really have much DD+ or DD+ Atmos content in my library

**Comment by kanokkk** [comment]
Overall it seems to be working a lot better, but in my testing i got an error loading Jung_E - below are my log.

time="02-17-2023 09:44:42" level=debug msg="ProcessWebhook:  Media type is: movie"
time="02-17-2023 09:44:42" level=debug msg="ProcessWebhook:  Media title is: Jung E"
time="02-17-2023 09:44:42" level=info msg="Processing media type: movie"
time="02-17-2023 09:44:42" level=debug msg="Event Router: Found edition: "
time="02-17-2023 09:44:42" level=debug msg="Event Router: Getting codec from data"
time="02-17-2023 09:44:42" level=debug msg="Codecs from plex received: 한국어 (EAC3 5.1), 한국어 (EAC3 5.1)"
time="02-17-2023 09:44:42" level=debug msg="Atmos: false - DD+: true"
time="02-17-2023 09:44:42" level=debug msg="Event Router: Received codec: DD+ Atmos"
time="02-17-2023 09:44:42" level=debug msg="Event Router: Got media type of: movie "
time="02-17-2023 09:44:42" level=debug msg="Event Router: media.play received"
time="02-17-2023 09:44:42" level=debug msg="Unloading ezBEQ profile"
time="02-17-2023 09:44:48" level=debug msg="sending ezbeq search request to /api/1/search?audiotypes=DD%2B+Atmos&years=2023"
time="02-17-2023 09:44:49" level=debug msg="Beq results: {d37ffd6911686fa5c8bf1866d7b323a8f1d49998\n_1910 last of us 2023 [DD+ Atmos] 66f97eed6421cf5831538762777e5c46724a84d6c3d8ce8505827a49ed1f67aa 6.5  100088}"
time="02-17-2023 09:44:49" level=debug msg="Beq results: {d37ffd6911686fa5c8bf1866d7b323a8f1d49998\n_3328 dog gone 2023 [DD+ Atmos] 945dfc5cf516dac6d196928fc7f902f11109fb1428b05346be3464951e4b120f 0  858408}"
time="02-17-2023 09:44:49" level=debug msg="Beq results: {d37ffd6911686fa5c8bf1866d7b323a8f1d49998\n_4556 junge 2023 [DD+ Atmos] 1678d7860ead948132f70ba3d823d7493bb3bb79302f308d135176bf4ff6f7d0 0  843794}"
time="02-17-2023 09:44:49" level=debug msg="Beq results: {d37ffd6911686fa5c8bf1866d7b323a8f1d49998\n_6829 true spirit 2023 [DD+ Atmos] 3dbcc4cae6f6421fb19d966d626677c6a9334f97922314c1ac46bd405c162ff4 0  739986}"
time="02-17-2023 09:44:49" level=debug msg="Beq results: {d37ffd6911686fa5c8bf1866d7b323a8f1d49998\n_7230 you people 2023 [DD+ Atmos] 163bc1b84fcaf349d0bf5cd04b0e48cd71f26e229e3a1c89442ca8f5df5f333d 0  866413}"
time="02-17-2023 09:44:49" level=debug msg="Beq results: {d37ffd6911686fa5c8bf1866d7b323a8f1d49998\n_7236 your place or mine 2023 [DD+ Atmos] b974f3e4c332b4b9cb4e5ab9f8b7b7697b993d15a92ed81989c921c499e4173c 0  703451}"
time="02-17-2023 09:44:49" level=debug msg="Beq results: {d37ffd6911686fa5c8bf1866d7b323a8f1d49998\n_7498 class 2023 [DD+ Atmos] e76e767484a6c2bf5e2d2d3a3d9f794b3438bbb093d737d92361549621ab7eb6 0  211116}"
time="02-17-2023 09:44:49" level=debug msg="Beq results: {d37ffd6911686fa5c8bf1866d7b323a8f1d49998\n_7860 lockwood & co 2023 [DD+ Atmos] 5b09e96731f9ea674e900b0ccc4d939eacca1f7e91c87c7da5caef0b819c7db2 0  213241}"
time="02-17-2023 09:44:49" level=debug msg="Beq results: {d37ffd6911686fa5c8bf1866d7b323a8f1d49998\n_7869 love to hate you 2023 [DD+ Atmos] 25ce85b2e267f80a4184df93cb9bd9cfce99427da7e92da6376b22adb9f04a04 0  137094}"
time="02-17-2023 09:44:49" level=debug msg="Beq results: {d37ffd6911686fa5c8bf1866d7b323a8f1d49998\n_8165 the last of us 2023 [DD+ Atmos] 9ccf51f54a8426f15630b05e94b78418134800e8f976ecb02dff410ae7ef7c09 0  100088}"
time="02-17-2023 09:44:49" level=debug msg="Beq results: {d37ffd6911686fa5c8bf1866d7b323a8f1d49998\n_8238 the snow girl 2023 [DD+ Atmos] c8bd272ff63af579eff7381f4d4e153b97580249e1cc7554b423bac3973c1066 0  215333}"
time="02-17-2023 09:44:49" level=debug msg="Beq results: {d37ffd6911686fa5c8bf1866d7b323a8f1d49998\n_8289 trial by fire 2023 [DD+ Atmos] 2e82b1995afad530bcfec90e3d6ed445654bb1a947f39b0424d1754fe641afb1 0  217699}"
time="02-17-2023 09:44:49" level=error msg="beq profile was not found in catalog"

In ezbeq this movie got DD+ Atmos

**Comment by kanokkk** [comment]
Would it be a bad idear to match, if the correct codec is not present at ezbeq,

DTS 5.1 to DTS-HD 5.1 & 7.1
DTS-HD 5.1 & 7.1 to DTS 5.1

**Comment by iloveicedgreentea** [comment]
Can you post the full log? Something should say getPlexMovieDb: Got tmdb ID from plex

One of the values, tmdb probably, is not matching for that title

Also no, that could be dangerous. Each codec has very different levels of boost and it could damage your subs

**Comment by kanokkk** [comment]
> Can you post the full log? Something should say getPlexMovieDb: Got tmdb ID from plex
> 
> One of the values, tmdb probably, is not matching for that title
> 
> Also no, that could be dangerous. Each codec has very different levels of boost and it could damage your subs

This was the whole log for this movie. I tried a couple more times and there is no search for "getPlexMovieDb" - it only make a search in ezbeq.

**Comment by iloveicedgreentea** [comment]
Okay then thats the issue Your Plex title does not have a TMDB id which is how it matches to ezbeq. Check your plex match/metadata and update it. Should be 843794
