### ISSUE TITLE
Feature Request - Configure what slot is used in ezbeq in config?

### ISSUE THREAD

**Issue by kchaing** [iloveicedgreentea/plex-webhook-automation#6]
Is it possible to be able to configure what preset slot is used when setting ezbeq filters? I have slot 1/2 with my two different house curves that I use for general music/content when there's no PEQ filter available. I normally use slot 3 or slot 4 to load up for stuff that is found in ezbeq.

**Comment by iloveicedgreentea** [comment]
I can add that

**Comment by iloveicedgreentea** [comment]
Please try using tag 2.0.5 and look at the readme for config changes

I added slots, arbitrary amount of devices, and a bunch of other improvements
